name: smart_space
description: Flutter package for ensuring a consistent visual rhythm across each screen.
version: 0.1.0
repository: https://github.com/ggalambas/smart_space

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: null